---
apiVersion: v1
kind: Service
metadata:
  name: statistics-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
  name: statistics-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: statistics-mongodb
    spec:
      containers:
      - env:
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggymetrics
                key: auth_mongodb_password
          - name: MONGODB_USER
            value: user
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggymetrics
                key: statistics_mongodb_password
          - name: MONGODB_DATABASE
            value: piggymetrics
        ports:
          - containerPort: 27017
        image: centos/mongodb-32-centos7
        name: statistics-mongodb
        resources: {}
      restartPolicy: Always
status: {}
